### ISSUE TITLE
Illegal invocation on transport file

### ISSUE THREAD

**Issue by felipeplets** [DataDog/browser-sdk#794]
Since April 9th I started seeing errors that I can't reproduce reaching my users and it seems be more frequently.

I'm using @datadog/browser-rum 2.7.1 which depends on @datadog/browser-core 2.7.1

The raw error is: 
```bash
TypeError: Illegal invocation
  at e.send(../../../src/transport/transport.ts:22:34)
  at e.flush(../../../src/transport/transport.ts:68:20)
  at apply(../../../src/transport/transport.ts:153:12)
  at n(../../src/helpers.ts:87:17)
```

Line 22 on the source map is: 
```typescript
    HttpRequest.prototype.send = function (data, size) {
        var url = this.withBatchTime ? addBatchTime(this.endpointUrl) : this.endpointUrl; // <== this one
        if (navigator.sendBeacon && size < this.bytesLimit) {
            var isQueued = navigator.sendBeacon(url, data);
            if (isQueued) {
                return;
            }
```
On file `@datadog/browser-core/esm/transport/transport.js`.

But this does not seem to make sense as the error is `e.send` so it is happening when send is called. 

It seems to happen in any browser (Chrome 70/79/80/89, Mobile Safari, Samsung Internet, Chrome Mobile are some examples). I could not reproduce it yet.

Any thoughts or ideas are welcome.

**Comment by bcaudan** [comment]
Hello @felipeplets,

From the source map, since it references ts files, it should probably map to the original sources [transport.ts@22](https://github.com/DataDog/browser-sdk/blob/v2.7.1/packages/core/src/transport/transport.ts#L22):
```ts
const isQueued = navigator.sendBeacon(url, data)
```                                                
which would make more sense.

From the [spec](https://w3c.github.io/beacon/#sec-processing-model), sendBeacon can send TypeError if there is an issue during url parsing.
Not sure what could go wrong here.

Did you upgrade the SDK version on April 9th?
If yes, which one were you using before?

If not, I would suggest you to go through [datadog support](https://www.datadoghq.com/support/) in order to exchange a bit more info about your application to help us diagnose the issue.

**Comment by felipeplets** [comment]
@bcaudan we have not updated it, we do daily deploys but DD was not updated for a couple of months. I've updated it this week to the latest version in order to try fixing the issue.

**Comment by bcaudan** [comment]
It could also worth checking if `navigator.sendBeacon` is not patched by another dependency. 
You could try to to fire one on your site from the browser console to see if you have a similar behavior.

**Comment by felipeplets** [comment]
@bcaudan tried it and I get true. As it happens in some cases and I can't reproduce I believe may be related to been patched by another dependency but based on some specific scenario. 

Another thing is that as the raw error says `e.send(` I believe this is actually related to the point in the code where send is called and not `sendBeacon`. I will take a look on enhancing logs to try to reproduce or better understand the issue.

**Comment by bcaudan** [comment]
>  I can't reproduce I believe may be related to been patched by another dependency but based on some specific scenario.

My tip for that would be to try to delete the API at the beginning of the page execution, to see if some dependency try to shim the API when it is not available.

> I believe this is actually related to the point in the code where send is called and not sendBeacon

I'll ping here when we will release the linked PRs, you could then upgrade your SDK version and see how it behaves.

**Comment by ronaldsmartin** [comment]
Thanks for looking into this! My company also started having the same issue, but slightly earlier: the reports started coming in on April 6, when we were using browser-core v1.12.4. We upgraded to v2.7.1 on April 9 and have continued to see the error.

Our bug tracker suggests that it occurs most often for Windows users on older versions of Chrome, but like @felipeplets we've seen it across different browsers and OSes.

`navigator.sendBeacon('https://www.datadoghq.com')` also returns `true` on our site.

**Comment by bcaudan** [comment]
the two linked PRs has been released in 2.7.4, let us know how it goes

**Comment by sychd** [comment]
Hello! We've bumped into same issue on our project, it started to appear ~15 days ago.
I didn't manage to reproduce it but, after reading this issue thread, updated version to the latest one.
Since update I do not see error so far

**Comment by felipeplets** [comment]
Thanks @bcaudan. We've updated the package yesterday. I will wait for the day until I close this issue.

**Comment by igrayson** [comment]
We're also getting this issue, as of a few weeks ago. We updated to 2.7.4 (confirmed!) and are still seeing it. Latest event came from `Chrome 72.0.3626`. This client fired three `Illegal Invocation`s in about 3 seconds, then went quiet. Our app is built and deployed with nextjs (webpack).
![image](https://user-images.githubusercontent.com/6943580/115874619-2487dd00-a3f9-11eb-8afd-a3edc078f371.png)

**Comment by BenoitZugmeyer** [comment]
@igrayson: In your screenshot, we can see that the exception is triggered at a place where `window.navigator.sendBeacon` is used followed by a `window.fetch` fallback, which is not done in our codebase. So, this is not the same issue, and probably not related to the RUM Browser SDK (as it does not instrument `navigator` nor `sendBeacon`)

**Comment by felipeplets** [comment]
Since upgrading, 48 hours ago, to the latest version (2.7.4) we have not seen this issue. Therefore I'm closing the issue.
